name: "GitHub Actions :: Playground :: GitHub Script Action :: Test"

on:
  push:
    branches: [main]

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Support longpaths"
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          path: kie-tools
          repository: tiagobento/kie-tools
          fetch-depth: 1
          ref: main

      - name: "Setup environment"
        uses: ./kie-tools/.github/actions/setup-env
        with:
          path: kie-tools

      - name: "Build"
        id: build
        env:
          WEBPACK__minimize: "false"
          WEBPACK__tsLoaderTranspileOnly: "false"
          KIE_TOOLS_BUILD__runLinters: "true"
          KIE_TOOLS_BUILD__runTests: "true"
          KIE_TOOLS_BUILD__runIntegrationTests: ${{ matrix.os == 'ubuntu-latest' }}
          KIE_TOOLS_BUILD__buildContainerImages: "true"
          KIE_TOOLS_BUILD__buildExamples: "true"
          KIE_TOOLS_BUILD__ignoreTestFailures: "true"
          KIE_TOOLS_BUILD__ignoreIntegrationTestFailures: "true"
          DISPLAY: ":99.0"
          START_SERVER_AND_TEST_INSECURE: "true"
        shell: bash
        run: |
          cd kie-tools
          pnpm install --workspace-root --strict-peer-dependencies=false -F 'kie-tools-root...'
