name: "Testing Google Chrome"
on:
  push:
    branches: [main]
jobs:
  run:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: "Install Fluxbox (Ubuntu only)"
        shell: bash
        run: |
          echo "STEP: Install Fluxbox (Ubuntu only)"
          cd ${{ inputs.working_dir }}
          if [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt-get -y install fluxbox > /dev/null 2>&1
          fi
  
      - name: "Start Xvfb (Ubuntu only)"
        shell: bash
        run: |
          echo "STEP: Start Xvfb (Ubuntu only)"
          cd ${{ inputs.working_dir }}
          if [ "${{ runner.os }}" == "Linux" ]; then
              /usr/bin/Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          fi
  
      - name: "Start Fluxbox (Ubuntu only)"
        shell: bash
        run: |
          echo "STEP: Start Fluxbox (Ubuntu only)"
          cd ${{ inputs.working_dir }}
          if [ "${{ runner.os }}" == "Linux" ]; then
              fluxbox -display :99 > /dev/null 2>&1 &
          fi
  
      - name: "Increase inotify watches (Ubuntu only)"
        shell: bash
        run: |
          echo "STEP: Increase inotify watches (Ubuntu only)"
          cd ${{ inputs.working_dir }}
          if [ "${{ runner.os }}" == "Linux" ]; then
            echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          fi
          
      - name: "Try google-chrome"
        shell: bash
        run: |
          export DISPLAY=:99
          google-chrome --enable-features=UnexpireFlagsM118 --allow-insecure-localhost
          sleep 10;
          kill $(pgrep google-chrome)
          exit 0
