name: "GitHub Actions :: Playground :: Run command"

on:
  push: 
    branches: [main]
  workflow_dispatch:
    inputs:
      command:
        type: string
        required: true
        description: ""

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Print contexts"
        shell: bash
        run: |
          echo "${{ toJson(github) }}"

      - name: "Run command"
        shell: bash
        run: |
          ${{ github.event.inputs.command }}
