name: "GitHub Actions :: Playground :: Run command"

on:
  workflow_dispatch:
    inputs:
      runner:
        type: string
        required: true
        description: ""
      shell:
        type: string
        required: true
        description: ""
      command:
        type: string
        required: true
        description: ""

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Run command"
        shell: bash
        run: |
          ${{ github.event.inputs.command }}